### ISSUE TITLE
Regression in `Changed#uptodate`?

### ISSUE THREAD

**Issue by liff** [sbt/util#113]
See the [discussion(https://github.com/sbt/sbt-scalariform/pull/57#issuecomment-319374696) in sbt/sbt-scalariform#57 for context.

This works on SBT 0.13.16 (`sbt.version=0.13.16` in `build.properties`; run `sbt bleh` to reproduce):

```scala
sbtPlugin := true

val bleh = taskKey[Unit]("bleh")

bleh := {
  import sbt.Cache.uriFormat
  val changed = new Changed[URI](streams.value.cacheDirectory / "bleh")
  val res = changed(_ => false, _ => true)(new URI("http://bogus"))
  println(s"changed=$res")
}
```

But converted and run on 1.0.0-RC3 it produces an error since the file does not exist/is empty:

```scala
sbtPlugin := true

val bleh = taskKey[Unit]("bleh")

bleh := {
  import sbt.util.CacheStore
  import sjsonnew.BasicJsonProtocol._
  val changed = new Changed[String](CacheStore(streams.value.cacheDirectory / "bleh"))
  val res = changed(_ => false, _ => true)("hello")
  println(s"changed=$res")
}
```

As @godenji pointed out, 0.13, `Changed` returns false on an exception but not in 1.0. Is this a regression or is `Changed` supposed to be used in a different manner in 1.0?

**Comment by eed3si9n** [comment]
Thanks for reporting this.

**Comment by eed3si9n** [comment]
As far as I can tell `Changed` is no longer used by sbt. So I think we will deprecate it during 1.x.

Here's how you can port `bleh`:

```scala
bleh := {
  import sbt.util.CacheImplicits._
  val f = Tracked.inputChanged[URI, Unit](streams.value.cacheDirectory / "bleh") {
    case (changed, in) => println(s"changed=$changed")
  }
  f(uri("http://bogus"))
}
```
