### ISSUE TITLE
check scalariform in travis-ci

### ISSUE THREAD

**Issue by xuwei-k** [sbt/util#7]
like this https://github.com/scalikejdbc/scalikejdbc/commit/b1e55a76d494dc367585

**Comment by dwijnand** [comment]
:+1:, though it would be nice if sbt-scalariform provided this task out the box

**Comment by eed3si9n** [comment]
we should put that in https://github.com/sbt/sbt-houserules

**Comment by dwijnand** [comment]
I'm proposing a fix for this in sbt/sbt (https://github.com/sbt/sbt/pull/2663), but I like the implementation in scalikejdbc better.

**Comment by xuwei-k** [comment]
https://github.com/sbt/util/commit/1527acc6c1f745ad18d33ff08cd7cdbefba3cc8e
