### ISSUE TITLE
jdk 7 compatibility

### ISSUE THREAD

**Issue by peiyuwang** [sbt/util#75]
Starting 2573c0f0921433f741801bf635bbb88da5f3b26a , `util-interface` is compiled/published using jdk8, which means in order to consume zinc >= `1.0.0-X7` we would have to start telling [pants](https://github.com/pantsbuild/pants/) users stop using jdk7, which i guess is not totally unreasonable given jdk7 reaches its eol for already 2 years? but honestly i don't know.

Would really appreciate we start with a plan and communicate first whichever decision we choose as opposed to drop immediately.

**Comment by eed3si9n** [comment]
sbt 1 modules will all be built using JDK 8.
